### ISSUE TITLE
Decode CRN

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#31]
Develop a java program to display **Batch**, **Department** & **Roll Number** of user input. User input should be 6-character string such as 710339, 650101, etc.

#_Example:_
**User Input:** 71AB39 - Not a valid CRN
**User Input:** 7103396 - Not a valid CRN
**User Input:** Nepal - Not a valid CRN
**User Input:** 710339 - Valid CRN
# **Decoded Output**
**Batch:** 2071
**Department:** Computer Engineering
**Roll No.:** 39

**Comment by milan604** [comment]
**Program**
package decodecrn;

import java.util.Scanner;
import java.util.regex.Pattern;

/**
 *
 * @author m-lan
 */
public class DecodeCrn {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String crn, dpt, dpt_name;
        Scanner input = new Scanner(System.in);
        System.out.println("Please Enter Your College Roll Number of 6 Digits(Sample:710315):");
        crn = input.next();
        if (Pattern.matches("[a-zA-Z]+", crn) == true || crn.length() > 6) {
            System.out.println("Invalid College Roll Number");
        } else {
            dpt = crn.substring(2, 4);
            if (dpt.equals("01")) {
                dpt_name = "Civil Engineering";
            } else if (dpt.equals("02")) {
                dpt_name = "Architecture";
            } else if (dpt.equals("03")) {
                dpt_name = "Computer Engineering";
            } else if (dpt.equals("04")) {
                dpt_name = "Electronics Engineering";
            } else {
                dpt_name = "Unknown";
            }
            System.out.println("Batch:20" + crn.substring(0, 2));
            System.out.println("Department:" + dpt_name);
            System.out.println("Rollno.:" + crn.substring(4, 6));
        }
    }
}
**Output**
![screenshot from 2017-08-10 14-24-51](https://user-images.githubusercontent.com/30483005/29161996-db8af236-7dd7-11e7-99df-2580314a717f.png)

![screenshot from 2017-08-10 15-29-54](https://user-images.githubusercontent.com/30483005/29164901-c8cd5a9a-7de0-11e7-85d7-02aefd645153.png)

**Comment by ErSKS** [comment]
@milan604 Display useful error message of the input **ABCDEF** : It's not a **CRN**.

**Comment by jagdish4249** [comment]
package stringinput;

import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Jagdish Duwal
 */
public class StringInput {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        int invalid=0; 
        String roll;
        roll = JOptionPane.showInputDialog("Enter your full roll no(eg.710310)\n");

        System.out.println();
        for(int i = 0 ; i< roll.length(); i++){
            char c = roll.charAt(i);
            int ascii = (int)c;
            //ascii value of 0 = 48 and 9 = 57
            boolean len = roll.length()==6;
            boolean number = ascii< 48 || ascii> 57;
            if(!len || number ) {
            invalid++;
            } 
        }
       
        if(invalid == 0){
            String batch;
            batch = roll.substring(0,2);
            System.out.printf("Batch: 20%s\n",batch);
        
            String department;
            department = roll.substring(2,4);
            switch(parseInt(department)){
                case 01:
                    department = "Civil Department";
                    break;

                case 02:
                    department = "Architechture Department";
                    break;

                case 03:
                    department = "Computer Department";
                    break;

                case 04:
                    department = "Electronics Department";
                    break;

                default:
                    department = "invalid input";

            }
            System.out.printf("Department: %s\n",department);

            String rollno;
            rollno = roll.substring(4);

            System.out.printf("Roll no: %s\n",rollno);
        }else{
            JOptionPane.showMessageDialog(null,"Please Enter your CRN");
        }
        
        
    }
    
}
![capture](https://user-images.githubusercontent.com/11315092/29165659-34308094-7de3-11e7-8cb7-d193fb728247.JPG)


![capture](https://user-images.githubusercontent.com/11315092/29165766-a1bdf394-7de3-11e7-9725-fb3bd4140bc0.JPG)

![capture](https://user-images.githubusercontent.com/11315092/29165809-caf8476e-7de3-11e7-9350-49605b7a09bf.JPG)

**Comment by rivab** [comment]
package day8tasklast;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Day8tasklast {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String crn;
        String department = "00";
        int roll, depart, batch;
        while (true) {
            crn = JOptionPane.showInputDialog("Enter your Roll no.");

            for (char c : crn.toCharArray()) {
                if (!Character.isDigit(c)) {
                    JOptionPane.showMessageDialog(null, "Roll no should be in number", "Try again", 1);
                    crn = JOptionPane.showInputDialog("Enter your Roll no.");
                    break;
                }
            }

            if (crn.length() != 6) {
                JOptionPane.showMessageDialog(null, "Number should be of 6 digits", "Try again", 1);
                continue;
            }

            batch = Integer.parseInt(crn.substring(0, 2));
            if (batch > 74) {
                JOptionPane.showMessageDialog(null, "Batch is grater than current year", "Invalid", 1);
                continue;
            }

            depart = Integer.parseInt(crn.substring(2, 4));
            if (depart == 1) {
                department = "Civil";
            } else if (depart == 2) {
                department = "Architecture";
            } else if (depart == 3) {
                department = "Computer";
            } else if (depart == 4) {
                department = "Architecture";
            } else {
                JOptionPane.showMessageDialog(null, "Unknown department", "Invalid", 1);
                continue;
            }

            roll = Integer.parseInt(crn.substring(4, 6));
            if (roll >= 50 || roll < 1) {
                JOptionPane.showMessageDialog(null, "Roll grater than 50 is not accepted", "Invalid", 1);
                continue;
            }

            JOptionPane.showMessageDialog(null, "Batch=20" + batch + "\nDepartment=" + department + "\nRoll No.=" + roll, "Your info", 1);
            break;
        }
    }
![day8last1](https://user-images.githubusercontent.com/30047861/29169970-4ecf5908-7df6-11e7-9645-a9569b92d109.JPG)
![day8last2](https://user-images.githubusercontent.com/30047861/29169969-4eb98ed4-7df6-11e7-8583-442265185a41.JPG)
![day8last3](https://user-images.githubusercontent.com/30047861/29169967-4eb78896-7df6-11e7-9687-2c4710ab8934.JPG)
![day8last4](https://user-images.githubusercontent.com/30047861/29169968-4eb927dc-7df6-11e7-83d6-3244ab4d9f13.JPG)

**Comment by karmi214** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day8task;

import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Anish
 */
public class Day8Task {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String crn, b = "", d = "", r = "";
        boolean f;
        do {
            f = true;
            crn = JOptionPane.showInputDialog("Enter your college roll number");
            if (crn.length() != 6) {
                JOptionPane.showMessageDialog(null, "The entered data is not valid", "Error", 0);
                f = false;
            } else {
                for (int i = 0; i < crn.length(); i++) {
                    char c = crn.charAt(i);
                    if (!Character.isDigit(c)) {
                        JOptionPane.showMessageDialog(null, "The entered data is not a number", "Error", 0);
                        f = false;
                        break;
                    }
                }
            }
            if (f) {
                b = crn.substring(0, 2);
                d = crn.substring(2, 4);
                r = crn.substring(4);
                switch (d) {
                    case "01":
                        d = "Architecture";
                        break;
                    case "02":
                        d = "Civil";
                        break;
                    case "03":
                        d = "Computer";
                        break;
                    case "04":
                        d = "Electronics & Communication";
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Incorrect department id", "Error", 0);
                        f = false;
                        break;

                }
            }
        } while (!f);
        JOptionPane.showMessageDialog(null, "Batch of: 20" + b + "\nDepartment: " + d + "\nRoll: " + r);

    }

}
![1](https://user-images.githubusercontent.com/24736628/29170598-2af58e28-7df9-11e7-932d-7c66a620e261.PNG)
![2](https://user-images.githubusercontent.com/24736628/29170606-2e92bff6-7df9-11e7-87ee-bdacaaaa5431.PNG)
![3](https://user-images.githubusercontent.com/24736628/29170610-316e1950-7df9-11e7-9e80-00df28b6e5d0.PNG)
![4](https://user-images.githubusercontent.com/24736628/29170612-3419244c-7df9-11e7-9d1b-c557e904f043.PNG)

**Comment by Sudan15423** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decode;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Dragon15423
 */
public class Decode {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here

        String roll = JOptionPane.showInputDialog("Enter your full roll no(eg.710310)\n");
        System.out.println("Your input =" + roll);

        if (roll.matches("[0-9]+") && roll.length() == 6) {
            System.out.println("Decoded Ouput");
            System.out.println("Batch: 20" + roll.substring(0, 2));
            System.out.print("Department: ");
            String com = roll.substring(2, 4);

            switch (com) {

                case "01":
                    System.out.println("Civil Engineering");
                    break;

                case "02":
                    System.out.println("Architecture Engineering");
                    break;

                case "03":
                    System.out.println("Computer Engineering");
                    break;

                case "04":
                    System.out.println("Electronics Engineering");
                    break;

                default:
                    System.out.println("not valid");
                    break;
            }
            System.out.println("Roll no.: " + roll.substring(4, 6));
        } else {
            JOptionPane.showMessageDialog(null, "Not a valid CRN", "Error", 0);
        }

    }

}
![input](https://user-images.githubusercontent.com/24761050/29171406-3e770fd2-7dfc-11e7-9413-86cdc3be8be9.PNG)
![output](https://user-images.githubusercontent.com/24761050/29171410-43d909c6-7dfc-11e7-9c78-5a2e8afeb1b3.PNG)
![invalidinput](https://user-images.githubusercontent.com/24761050/29171416-47ae56e6-7dfc-11e7-9d6b-da0502be68e5.PNG)
![invalid](https://user-images.githubusercontent.com/24761050/29171429-4e7fa7fe-7dfc-11e7-8049-4c89b2965983.PNG)

**Comment by sajanbasnet75** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decodecrn;

import javax.swing.JOptionPane;

/**
 *
 * @author LORDsajan
 */
public class DecodeCrn {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String test2;
        OUTER:
        do {
            String s8;
            String dep;
            s8 = JOptionPane.showInputDialog("Enter College RollNo");

            if (s8.length() == 6 && s8.matches("[0-9]+")) {
                String s9 = s8.substring(0, 2);
                String s10 = s8.substring(3, 4);
                String s11 = s8.substring(4, 6);
                switch (s10) {
                    case "1":
                        dep = "Civil Engineering";
                        break;
                    case "2":
                        dep = "Architect";
                        break;
                    case "3":
                        dep = "Computer Engineering";
                        break;
                    case "4":
                        dep = "Electronics Engineering";
                        break;
                    default:
                        System.out.println("invalid rollno");
                        break OUTER;
                }
                System.out.println("DECODED OUTPUT");
                System.out.println("Batch: 20" + s9);
                System.out.println("Department: " + dep);
                System.out.println("RollNo: " + s11);
                test2 = "true";
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Input", "Oops", 2);
                test2 = "false";
            }
        } while (test2.equals("false"));

    }

}


![111](https://user-images.githubusercontent.com/22407698/29173855-45873e8e-7e04-11e7-9e1f-7b93069c11ee.PNG)
![112](https://user-images.githubusercontent.com/22407698/29173856-45897f5a-7e04-11e7-9a72-49da40b48cb8.PNG)
![in1](https://user-images.githubusercontent.com/22407698/29175090-d77295ac-7e07-11e7-9a85-89cc44dee04b.PNG)
![in2](https://user-images.githubusercontent.com/22407698/29175091-d772ab0a-7e07-11e7-9237-ed9f0837da28.PNG)

**Comment by ghost** [comment]
package day08lastone;

import javax.swing.JOptionPane;

/**
 *
 * @author Samikshya
 */
public class Day08Lastone {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String crn;
        String department = "00";
        int roll, depart, batch;
        while (true) {
            crn = JOptionPane.showInputDialog("Enter your Roll no.");

            for (char c : crn.toCharArray()) {
                if (!Character.isDigit(c)) {
                    JOptionPane.showMessageDialog(null, "Roll no should be in number", "Try again", 1);
                    crn = JOptionPane.showInputDialog("Enter your Roll no.");
                    break;
                }
            }

            if (crn.length() != 6) {
                JOptionPane.showMessageDialog(null, "Number should be of 6 digits", "Try again", 1);
                continue;
            }

            batch = Integer.parseInt(crn.substring(0, 2));
            if (batch > 74) {
                JOptionPane.showMessageDialog(null, "Batch is grater than current year", "Invalid", 1);
                continue;
            }

            depart = Integer.parseInt(crn.substring(2, 4));
            if (depart == 1) {
                department = "Civil";
            } else if (depart == 2) {
                department = "Architecture";
            } else if (depart == 3) {
                department = "Computer";
            } else if (depart == 4) {
                department = "Architecture";
            } else {
                JOptionPane.showMessageDialog(null, "Unknown department", "Invalid", 1);
                continue;
            }

            roll = Integer.parseInt(crn.substring(4, 6));
            if (roll >= 50 || roll < 1) {
                JOptionPane.showMessageDialog(null, "Roll grater than 50 is not accepted", "Invalid", 1);
                continue;
            }

            JOptionPane.showMessageDialog(null, "Batch=20" + batch + "\nDepartment=" + department + "\nRoll No.=" + roll, "Your info", 1);
            break;
        }
![capture](https://user-images.githubusercontent.com/30020107/29175014-b1b0107e-7e07-11e7-9cd2-cdf59701ca25.JPG)
![capturee](https://user-images.githubusercontent.com/30020107/29175036-b5684614-7e07-11e7-8bb1-6ffc13089b51.JPG)

**Comment by syslin** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toidentifyuser;

import java.util.Scanner;

/**
 *
 * @author dell
 */
public class ToIdentifyUser {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String roll, batch, dept, dept_nm;
        int b;
        Scanner crn = new Scanner(System.in);
        System.out.println("enter the roll number: eg. 710340");
        roll = crn.next();
        while (true) {
            for (char c : roll.toCharArray()) {
                if (!Character.isDigit(c)) {
                    System.out.println("input must be a number of 6 digits");
                    roll = crn.next();
                    break;
                }
            }
            if (roll.length() != 6) {
                System.out.println("enter the number of 6 digits");
                roll = crn.next();
                continue;
            }

            batch = roll.substring(0, 2);
            if (Integer.parseInt(batch) > 74) {
                System.out.println("year greater than present year");
                break;
            }

            dept = roll.substring(3, 4);
            switch (dept) {
                case "1":
                    dept_nm = "Civil department";
                    break;
                case "2":
                    dept_nm = "ArchitectureDepartment";
                    break;
                case "3":
                    dept_nm = "Computer Department";
                    break;
                case "4":
                    dept_nm = "Electronics Department";
                    break;
                default:
                    dept_nm = "Not in the list";
                    break;
            }
            String r = roll.substring(4, 6);
            if (Integer.parseInt(r) >= 50 || Integer.parseInt(r) < 1) {
                System.out.println("invalid roll");
                break;
            }
            System.out.println("Batch:20" + batch);
            System.out.println("department:" + dept_nm);
            System.out.println("your roll number is:" + r);
            break;
        }
    }
}
![captur5](https://user-images.githubusercontent.com/30019204/29176331-45a7f03c-7e0b-11e7-926a-738e2adb31c6.PNG)
![capture6](https://user-images.githubusercontent.com/30019204/29176337-48e2baac-7e0b-11e7-9d50-ee770cb02044.PNG)

**Comment by kajalmaharjan** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day8task9;

import javax.swing.JOptionPane;

/**
 *
 * @author kajal
 */
public class Day8Task9 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String crn, department = "00";
        int batch, roll, depart;

        crn = JOptionPane.showInputDialog("Enter your roll number:");
        if (crn.length() != 6) {
            JOptionPane.showInputDialog("Enter your correct roll number:");
        }

        for (char c : crn.toCharArray()) {
            if (!Character.isDigit(c)) {
                crn = JOptionPane.showInputDialog("Enter your correct Roll no.");
                continue;
            }
        }

        batch = Integer.parseInt(crn.substring(0, 2));
        if (batch > 74) {
            JOptionPane.showInputDialog("Enter the correct roll no:");
        }

        depart = Integer.parseInt(crn.substring(2, 4));
        if (depart == 1) {
            department = "Civil";
        } else if (depart == 2) {
            department = "Architecture";
        } else if (depart == 3) {
            department = "Computer";
        } else if (depart == 4) {
            department = "Architecture";
        } else {
            JOptionPane.showMessageDialog(null, "Unknown department", "Invalid", 1);

        }

        roll = Integer.parseInt(crn.substring(4, 6));
        if (roll >= 50 || roll < 1) {
            JOptionPane.showMessageDialog(null, "Roll grater than 50 is not accepted", "Invalid", 1);

        }
        JOptionPane.showMessageDialog(null, "Batch = 20" + batch + "\nDepartment=" + department + "\nRoll No.= " + roll, "crn", 1);
    }
}
![1](https://user-images.githubusercontent.com/30050067/29177088-746cb93c-7e0d-11e7-93ba-723f6d24a250.png)
![2](https://user-images.githubusercontent.com/30050067/29177101-7b817dde-7e0d-11e7-8acf-1d93a564edc6.png)
![3](https://user-images.githubusercontent.com/30050067/29177111-82432cf8-7e0d-11e7-8470-f2d3faeed07f.png)
![4](https://user-images.githubusercontent.com/30050067/29177128-8a159e2a-7e0d-11e7-95fb-b3c1c5857620.png)

**Comment by maheshyakami** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decodecrn;

import javax.swing.JOptionPane;

/**
 *
 * @author mahesh
 */
public class DecodeCRN {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String CRN = new String();
        CRN = JOptionPane.showInputDialog("Enter CRN");
        System.out.println(CRN);
        if (!CRN.matches("[0-9]+") || CRN.length() > 6) {
            JOptionPane.showMessageDialog(null, "Invalid number");
        } else {
            String dept;
            dept = CRN.substring(2, 4);
            switch (dept) {
                case "01":
                    dept = "Civil";
                    break;
                case "02":
                    dept = "Architecture";
                    break;
                case "03":
                    dept = "Computer";
                    break;
                case "04":
                    dept = "Electronics and Communication";
                    break;
                default:
                    dept = "Unspecified Department";
                    break;
            }
            JOptionPane.showMessageDialog(null, "Batch: " + CRN.substring(0, 2) + "\nDepartment: " + dept + "\nRoll No: " + CRN.substring(4));
        }

    }

}
<img width="390" alt="screen shot 2017-08-10 at 9 09 31 pm" src="https://user-images.githubusercontent.com/30024656/29178229-a573f22c-7e10-11e7-93b2-18d1cbb001ec.png">
<img width="278" alt="screen shot 2017-08-10 at 9 11 42 pm" src="https://user-images.githubusercontent.com/30024656/29178241-adc92500-7e10-11e7-976f-bd03f26c906f.png">
<img width="387" alt="screen shot 2017-08-10 at 9 13 45 pm" src="https://user-images.githubusercontent.com/30024656/29178293-d7259104-7e10-11e7-824f-5793fa6decd7.png">
<img width="264" alt="screen shot 2017-08-10 at 9 13 51 pm" src="https://user-images.githubusercontent.com/30024656/29178297-d952b33a-7e10-11e7-8bd0-53c8ce51e1d5.png">

**Comment by rabina12** [comment]
package day8a2;

import javax.swing.JOptionPane;

/**
 *
 * @author Awal
 */
public class Day8a2 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String crn = JOptionPane.showInputDialog("Enter your full roll no(eg.710101)\n");
        System.out.println("Your input =" + crn);

        if (crn.matches("[0-9]+") && crn.length() == 6) {
            System.out.println("Decoded Ouput");
            System.out.println("Batch: 20" + crn.substring(0, 2));
            System.out.print("Department: ");
            String s = crn.substring(2, 4);

            switch (s) {

                case "01":
                    System.out.println("Architecture Engineering");
                    break;

                case "02":
                    System.out.println("Civil Engineering");
                    break;

                case "03":
                    System.out.println("Computer Engineering");
                    break;

                case "04":
                    System.out.println("Electronics Engineering");
                    break;

                default:
                    System.out.println("not valid");
                    break;
            }
            System.out.println("Roll no.: " + crn.substring(4, 6));
        } else {
            JOptionPane.showMessageDialog(null,"Roll no should be in numbers");
        }

    }

}
![capture1](https://user-images.githubusercontent.com/30483091/29180891-ee8d4744-7e18-11e7-9013-5a9b9a3a860b.PNG)
![capture1a](https://user-images.githubusercontent.com/30483091/29180893-f11f6e56-7e18-11e7-8cfa-a32bb68f4250.PNG)
![capture1c](https://user-images.githubusercontent.com/30483091/29180896-f5c31d2c-7e18-11e7-902a-9f6b65e96647.PNG)

**Comment by RakenShahi** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decode;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Decode {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String r;
        Scanner st = new Scanner(System.in);
        System.out.println("Enter your college roll no(eg.710327) : ");
        r = st.next();
        if (r.matches("[0-9]+") && r.length() == 6) {
            System.out.println("\nDecoded Ouput");
            System.out.println("Batch:20" + r.substring(0, 2));
            System.out.print("Department:");
            String check = r.substring(2, 4);
              switch (check) {
                case "01":
                    System.out.println("Civil Engineering");
                    break;
                case "02":
                    System.out.println("Architecture Engineering");
                    break;
                case "03":
                    System.out.println("Computer Engineering");
                    break;
                case "04":
                    System.out.println("Electronics Engineering");
                    break;
                default:
                    System.out.println("not valid");
                    break;
            }
            System.out.println("Roll no.:" + r.substring(4, 6));
        } else {
            System.out.println("Invalid roll number");;
        }
    }
}

**OUTPUT**
![decode1](https://user-images.githubusercontent.com/30067218/29181535-3ff23426-7e1b-11e7-9b71-141b91550078.PNG)
![decode2](https://user-images.githubusercontent.com/30067218/29181567-57b3d0c4-7e1b-11e7-85b8-c46e1657429a.PNG)

**Comment by ajay987** [comment]
public static void main(String[] args) {
        // TODO code application logic here
        String str;
        int cg, ch, rn;

        str = JOptionPane.show
![op1](https://user-images.githubusercontent.com/26328626/29181721-ea355210-7e1b-11e7-9815-f44e57f4dc9f.PNG)
![op2](https://user-images.githubusercontent.com/26328626/29181719-e9af7866-7e1b-11e7-82ec-c04015286084.PNG)
![op3](https://user-images.githubusercontent.com/26328626/29181718-e9ab709a-7e1b-11e7-9891-0ef01b930156.PNG)
![op2](https://user-images.githubusercontent.com/26328626/29181734-f2463e6a-7e1b-11e7-8a8e-5843442d5f7e.PNG)
![op5](https://user-images.githubusercontent.com/26328626/29181736-f3261b20-7e1b-11e7-8667-f8da430dc781.PNG)
![op6](https://user-images.githubusercontent.com/26328626/29181739-f3dbde60-7e1b-11e7-9c5f-1eaa6079baf6.PNG)





 String str;
        int cg, ch, rn;

        str = JOptionPane.showInputDialog("Enter your id number");
        if (str.length() == 6) {
            cg = Integer.parseInt(str.substring(0, 2));
            System.out.println("Batch:20" + cg);
            ch = Integer.parseInt(str.substring(2, 4));
            if (ch == 01) {
                System.out.println("Department:Civil Engineering");
            } else if (ch == 02) {
                System.out.println("Department:Architecture");
            } else if (ch == 03) {
                System.out.println("Department:Computer Engineering");
            } else if (ch == 04) {
                System.out.println("Department:Electronics Engineering");
            }
            rn = Integer.parseInt(str.substring(4, 6));
            System.out.println("Roll No:" + rn);
            String sp = "true";
        } else {
            JOptionPane.showMessageDialog(null, "not valid");

        }

    }

**Comment by ErSKS** [comment]
I saw your coding diversity. Try to understand and write as clean & atomic as you can. Still I found error on your code, check your solution again.

@milan604 7103ab ab is not a roll number
@jagdish4249 Ok
@rivab 7103ab - java.lang.NumberFormatException
@karmi214 Ok
Susan Ok
@sajanbasnet75 Ok
@kajalmaharjan After 1st mistake attempt, your code doesn't function well

_Note:- Try to find out bug of your friend's code too._
