### ISSUE TITLE
Develop - Fibonacci Number Checker

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#35]
Develop a method **static boolean isFibonacciNumber(int n)**
```
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
```

**Comment by milan604** [comment]
package finonaccichecker;

/**
 *
 * @author m-lan
 */
public class FinonacciChecker {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        System.out.println("Checking Fibonacci Number...");
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }

    static boolean isFibonacciNumber(int n) {
        return isPerfectSquare(5 * n * n + 4) || isPerfectSquare(5 * n * n - 4);
    }
    static boolean isPerfectSquare(int n) {
        int Sq = (int) Math.sqrt(n);
        return (Sq * Sq == n);
    }
}

![screenshot from 2017-08-13 14-44-15](https://user-images.githubusercontent.com/30483005/29248521-dfbd5b14-8039-11e7-84df-62a45043b57a.png)

**Comment by jagdish4249** [comment]
package fibcheck;


import java.util.Scanner;


/**
 *
 * @author Jagdish Duwal
 */
public class FibCheck {

    /**
     * @param args the command line arguments
     */
    
    static boolean isFibonacciNumber(int x ){
           
       
        int a = 0, b = 1,c,pos=0;
    if(x<a) {
        System.out.println("invalid input");

    }else{

        while(x>=a){
             c= a+b;
                    a=b;
                    b=c;
                    if(x==a){
                        pos++;
                        break;
                    }

        }
 }
   if(pos > 0 ) return true;
   else return false;

    }
   
    
    
    
    public static void main(String[] args) {
        int x;

         System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }
}
![capture](https://user-images.githubusercontent.com/11315092/29249268-0870e456-804c-11e7-82c8-3b246128fd6d.JPG)

**Comment by karmi214** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibonaciinumberchecker;

/**
 *
 * @author Anish
 */
public class FibonaciiNumberChecker {

    static boolean isFibonacciNumber(int n) {
        int f1 = 0, f2 = 1;
        boolean f = false;
        while (n >= f1) {
            if (n == f1) {
                f = true;
                break;
            }
            f2 = f1 + f2;
            f1 = f2 - f1;
        }
        return f;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }

}
![f](https://user-images.githubusercontent.com/24736628/29249558-3a909db4-8051-11e7-81bf-4b2dbd533cee.PNG)

**Comment by RakenShahi** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibonaccicheck;

/**
 *
 * @author DELL
 */
public class FibonacciCheck {

    static boolean iPS(int x) {
        int s = (int) Math.sqrt(x);
        return (s * s == x);
    }

    static boolean isFibonacciNumber(int n) {
        return iPS(5 * n * n + 4)
                || iPS(5 * n * n - 4);
    }

    public static void main(String[] args) {
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }
}
 
**OUTPUT**
![fibonaccicheck](https://user-images.githubusercontent.com/30067218/29249585-4fb21dac-8052-11e7-9c7c-743639fb99a5.PNG)

**Comment by SusanCB** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task10.pkg2;

/**
 *
 * @author nissus
 */
public class Task102 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
       
     System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));  
    }
static boolean isFibonacciNumber(int n){
int a=0,b=1,c=0,count=0;
if(n<a) {
System.out.println("invalid input");

}
else 
  {
while(n>=a){
      c= a+b;
             a=b;
             b=c;
             if(n==a){
                 count++;
                 break;
             }

 }
  }
if (count>0){
return true;
}
else {
return false;
}

}
}


    
![fib2](https://user-images.githubusercontent.com/30483070/29250103-5051069c-805c-11e7-9897-a009b833a727.PNG)

**Comment by ghost** [comment]
package fibono;

/**
 *
 * @author Samikshya
 */
public class FinoChecker {

    static boolean isFibonacciNumber(int n) {
        int n1 = 0, n2 = 1;
        boolean f = false;
        while (n >= n1) {
            if (n == n1) {
                f = true;
                break;
            }
            n2 = n1 + n2;
            n1 = n2 - n1;
        }
        return f;
    }
}
public class FiboNo {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
}
      
![capture](https://user-images.githubusercontent.com/30020107/29250219-516bb9c6-805e-11e7-810f-7facb05d7c9d.JPG)

    }

}

**Comment by Sudan15423** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tasks;



/**
 *
 * @author Dragon15423
 */
public class Tasks {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        // TODO code application logic here

        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }

    static boolean isFibonacciNumber(int n) {

        int x, y = 1, z = 0;
        while (y < n) {
            x = z;
            z = y;
            y += x;
        }
        return y == n;

    }

}
![task](https://user-images.githubusercontent.com/24761050/29250431-09d28b4a-8062-11e7-90c3-6f72b5e5b999.PNG)

**Comment by kajalmaharjan** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fabonacciiseries;

/**
 *
 * @author kajal
 */
public class FabonacciiSeries {

    static boolean isFibonacciNumber(int n) {
        int n1 = 0, n2 = 1, n3, f = 0;

        if (n < n1) {
            System.out.println("invalid input");
        } else {
            while (n >= n1) {

                n3 = n1 + n2;

                n1 = n2;
                n2 = n3;
                if (n == n1) {
                    f++;
                    break;
                }
            }
        }
        if (f > 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        int n;

        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }

}
![123](https://user-images.githubusercontent.com/30050067/29250987-4e9f0672-806c-11e7-8926-8bbced741658.png)

**Comment by rabina12** [comment]
public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }

    static boolean isFibonacciNumber(int n) {

        int x, y = 1, z = 0;
        while (y < n) {
            x = z;
            z = y;
            y += x;
        }
        return y == n;
    }

}
![fs](https://user-images.githubusercontent.com/30483091/29251067-7c878f58-806e-11e7-9b6e-225a2fa4b10c.PNG)

**Comment by kiir33** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibonaccicheck;

/**
 *
 * @author Kiran
 */
public class FibonacciCheck {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("Checking Fibonacci number...");
        System.out.println("Fibonacci Check:0 true:"+ fibFunc(0));
        System.out.println("Fibonacci Check:1 true:"+ fibFunc(1));
        System.out.println("Fibonacci Check:2 true:"+ fibFunc(2));
        System.out.println("Fibonacci Check:3 true:"+ fibFunc(3));
        System.out.println("Fibonacci Check:12 false:"+ fibFunc(12));
        System.out.println("Fibonacci Check:13 false:"+ fibFunc(13));
        System.out.println("Fibonacci Check:21 true:"+ fibFunc(21));
        System.out.println("Fibonacci Check:22 false:"+ fibFunc(22));
        
    }
    static boolean fibFunc(int n){
        int a=0, b=1, c;
        while(a<=n) {
            if(a==n)
                return true;
            c=a+b;
            a=b;
            b=c;
        }
        return false;
    }   
}

**Output:**
![capturefibonacci](https://user-images.githubusercontent.com/30041751/29251142-d5f63a66-806f-11e7-82cc-5bd582856748.PNG)

**Comment by sarumdr** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibocheck;

/**
 *
 * @author sarumdr
 */
public class Fibocheck {

    /**
     * @param args the command line arguments
     */
    static boolean isFibonacciNumber(int n) {
        int a = 0, b = 1, c, pos = 0;
        if (n < a) {
            System.out.println("invalid input");

        } else {
            while (n >= a) {
                c = a + b;
                a = b;
                b = c;

                if (n == a) {
                    pos++;
                    break;
                }
            }
        }
        if (pos > 0) {
            return true;
        } else {
            return false;
        }
    }

    public static void main(String[] args) {
        // TODO code application logic here

        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }

}

OUTPUT
![image](https://user-images.githubusercontent.com/29326121/29251345-fec9a7f4-8072-11e7-88fa-d62c4176272f.png)

**Comment by rivab** [comment]
package day10fibonaccichecker;

/**
 *
 * @author DELL
 */
public class Day10fibonacciChecker {

    /**
     * @param args the command line arguments
     */
    static boolean isFibonacciNumber(int n) {
        int n1 = 0, n2 = 1, n3, f = 0;
        if (n < n1) {
            System.out.println("Fibonacci of negative number isnot possible");
        } else {
            while (n >= n1) {

                n3 = n1 + n2;

                n1 = n2;
                n2 = n3;
                if (n == n1) {
                    f++;
                    break;
                }
            }
        }
        if (f > 0) {
            return true;
        } else {
            return false;
        }
    }

    public static void main(String[] args) {
        // TODO code application logic here
        int n;
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }

}
![day10](https://user-images.githubusercontent.com/30047861/29257506-5ef56d02-80d2-11e7-8b92-11292cbffa74.JPG)

**Comment by ajay987** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checker35;

import java.util.Scanner;

/**
 *
 * @author Dell
 */
public class Checker35 {

    static boolean isfibonnaccinumber(int n) {
        int f0 = 0, f1 = 1;
        while (f0 <= n) {
            if (f0 == n) {
                return true;
            }
            f1 = f1 + f0;
            f0 = f1 - f0;

        }
        return false;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("1 true :" + isfibonnaccinumber(1));
        System.out.println("2 true :" + isfibonnaccinumber(2));
        System.out.println("3 true :" + isfibonnaccinumber(3));
        System.out.println("4 false :" + isfibonnaccinumber(4));
        System.out.println("5 true :" + isfibonnaccinumber(5));
        System.out.println("8 true :" + isfibonnaccinumber(8));
        System.out.println("11 false :" + isfibonnaccinumber(11));
        System.out.println("21 true :" + isfibonnaccinumber(21));
    }

}
![fibo](https://user-images.githubusercontent.com/26328626/29262996-b831f02e-80f6-11e7-85b3-bffc3b41fc7b.PNG)

**Comment by sthaanu** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibonaciicheck;

/**
 *
 * @author admin
 */
public class FibonaciiCheck {

    public static boolean isFibonacciNumber(int n) {
        int fib1 = 0;
        int fib2 = 1;
        do {
            int saveFib1 = fib1;
            fib1 = fib2;
            fib2 = saveFib1 + fib2;
        } while (fib2 < n);

        if (fib2 == n) {
            return true;
        } else {
            return false;
        }

    }

    public static void main(String[] args) {
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }
}
![capture](https://user-images.githubusercontent.com/30022783/29263329-060f14ba-80f8-11e7-9360-170631330a8d.PNG)

**Comment by sthaanu** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fibonaciicheck;

/**
 *
 * @author admin
 */
public class FibonaciiCheck {

    public static boolean isFibonacciNumber(int n) {
        int fib1 = 0;
        int fib2 = 1;
        do {
            int Fib1 = fib1;
            fib1 = fib2;
            fib2 = Fib1 + fib2;
        } while (fib2 < n);

        if (fib2 == n) {
            return true;
        } else {
            return false;
        }

    }

    public static void main(String[] args) {
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }
}
![capture](https://user-images.githubusercontent.com/30022783/29263410-553e807a-80f8-11e7-9acd-d89cb637f2e9.PNG)

**Comment by syslin** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package settergetter;

/**
 *
 * @author dell
 */
public class FibinocSeries {

    public static void main(String[] args) {
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }

    static boolean isFibonacciNumber(int n) {

        int a = 0, b = 1, c, count = 0;
        while (n >= a) {
            c = a + b;
            a = b;
            b = c;
            if (n == a) {
                count++;
                break;

            }

        }
        if (count > 0) {
            return true;
        } else {
            return false;
        }
    }

}
![111](https://user-images.githubusercontent.com/30019204/29263644-71a15cb4-80f9-11e7-8bde-9e331baf6bfe.PNG)

**Comment by sajanbasnet75** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication73;

/**
 *
 * @author LORDsajan
 */
public class JavaApplication73 {

    static boolean isFibonacaii(int x) {
        int a = 0, b = 1, c, d = 0;
        while (x >= a) {
            if (x < 0) {
                System.out.println("Invalid input");
                break;
            } else {
                c = a + b;
                a = b;
                b = c;
                if (x == a) {
                    return true;
                }
            }
        }
        return false;
    }

    public static void main(String[] args) {
        System.out.println("1 true:" + isFibonacaii(1));
        System.out.println("2 true:" + isFibonacaii(2));
        System.out.println("3 true:" + isFibonacaii(3));
        System.out.println("4 false:" + isFibonacaii(4));
        System.out.println("5 true:" + isFibonacaii(5));
        System.out.println("8 true:" + isFibonacaii(8));
        System.out.println("11 false:" + isFibonacaii(11));
        System.out.println("21 true:" + isFibonacaii(21));

    }
}
![capture](https://user-images.githubusercontent.com/22407698/29263880-94c2446e-80fa-11e7-912d-db361c56bc26.PNG)

**Comment by luckydivya** [comment]
package fibonacci;

/**
 *
 * @author PC
 */
public class Fibonacci {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));
    }

    static boolean isFibonacciNumber(int n) {

        int x, y = 1, z = 0;
        while (y < n) {
            x = z;
            z = y;
            y += x;
        }
        return y == n;
    }

}
}

}
![fibonacci pattern](https://user-images.githubusercontent.com/30065565/29275213-16d2aea6-812a-11e7-8e1a-f2f0ed0f0641.PNG)

**Comment by rituratnam** [comment]
CODE:
package fibonacci;

/**
 *
 * @author User
 */
public class Fibonacci {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
 // TODO code application logic here
 System.out.println("1 true:" + isFibonacciNumber(1));
System.out.println("2 true:" + isFibonacciNumber(2));
System.out.println("3 true:" + isFibonacciNumber(3));
System.out.println("4 false:" + isFibonacciNumber(4));
System.out.println("5 true:" + isFibonacciNumber(5));
System.out.println("11 false:" + isFibonacciNumber(11));
System.out.println("21 true:" + isFibonacciNumber(21));
}
static boolean isFibonacciNumber(int n) {

 int x, y = 1, z = 0;
 while (y < n) {
     x = z;
     z = y;
     y += x;
 }
 return y == n;
}
}
Output
![fibonacci](https://user-images.githubusercontent.com/30037739/29280431-eb16fc0c-813a-11e7-9ec4-c6c935685239.PNG)

**Comment by Rajjushrestha** [comment]
public class Fibonacci {

    static boolean isFibonacciNumber(int n) {
        int n1 = 0, n2 = 1, n3, f = 0;

        if (n < n1) {
            System.out.println("invalid input");
        } else {
            while (n >= n1) {

                n3 = n1 + n2;

                n1 = n2;
                n2 = n3;
                if (n == n1) {
                    f++;
                    break;
                }
            }
        }
        if (f > 0) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        int n;

        System.out.println("1 true:" + isFibonacciNumber(1));
        System.out.println("2 true:" + isFibonacciNumber(2));
        System.out.println("3 true:" + isFibonacciNumber(3));
        System.out.println("4 false:" + isFibonacciNumber(4));
        System.out.println("5 true:" + isFibonacciNumber(5));
        System.out.println("11 false:" + isFibonacciNumber(11));
        System.out.println("21 true:" + isFibonacciNumber(21));

    }
![fb](https://user-images.githubusercontent.com/30023827/29320170-1bb3cafa-81f6-11e7-84a5-32a8d390ce8f.PNG)
