### ISSUE TITLE
Develop - Lucky7 Game

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#40]
+ Using Random Number between 0-9
+ Analyse Loop : which is better, for or while?

**Hint:-** 
```
Random r = new Random();
sout(r.nextInt(10));
```

**Comment by milan604** [comment]
package luckyseven;

import java.util.Random;

import javax.swing.JOptionPane;

/**
 *
 * @author m-lan
 */
public class LuckySeven {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        int x, y, z, count = 0;
        String key;
        while (true) {
            key = JOptionPane.showInputDialog("Enter G to generate (any key to exit)");
            if (key.equalsIgnoreCase("G")) {
                Random r = new Random();
                x = r.nextInt(10);
                if (x == 7) {
                    count++;
                    switch (count) {
                        case 1:
                            JOptionPane.showMessageDialog(null, "7\nYou are Lucky 7");
                            break;
                        case 2:

                            JOptionPane.showMessageDialog(null, "77\nYou are Super Lucky 7");
                            break;
                        case 3:
                            JOptionPane.showMessageDialog(null, "777\nYou are Awesome Lucky 7");
                            break;
                        default:
                            break;
                    }
                } else {
                    count--;
                    if (count <= 0) {
                        count = 0;
                    }
                    JOptionPane.showMessageDialog(null, "Your Number is " + x + " Try Again...");
                }

            } else {
                break;
            }

        }

    }

}

![screenshot from 2017-08-16 09-19-23](https://user-images.githubusercontent.com/30483005/29346310-1be9756a-8264-11e7-9728-6ed37057346d.png)
![screenshot from 2017-08-16 12-28-16](https://user-images.githubusercontent.com/30483005/29350464-6ef7b8ec-827e-11e7-90a9-c2a7cdf26792.png)

![screenshot from 2017-08-16 09-19-23](https://user-images.githubusercontent.com/30483005/29350564-bec1ece4-827e-11e7-912d-79058f8f5286.png)

![screenshot from 2017-08-16 09-20-00](https://user-images.githubusercontent.com/30483005/29346317-2b59f8a8-8264-11e7-88aa-0e7ce9b0e810.png)

**Comment by Roshantwanabasu** [comment]
**Code:**
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package luckyseven;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author NiiRosh
 */
public class LuckySeven {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Random r = new Random();
        String ch = "y";
        JOptionPane.showMessageDialog(null, "Welcome to Lucky 7 Game\nClick on ok to generate 7");
        while (ch.equalsIgnoreCase("y")) {
            int x = r.nextInt(10);

            if (x == 7) {
                JOptionPane.showMessageDialog(null, "Congratulation!!! You generated 7\nYou are lucky");
            } else {
                JOptionPane.showMessageDialog(null, "Sorry you generated:" + x + "\nBetter luck next time");
            }
            ch = JOptionPane.showInputDialog("Do you want to try your luck again??(y/n)");
        }
    }

}

**Output:**
![welcome7](https://user-images.githubusercontent.com/30483063/29351047-b90d64e8-8280-11e7-82de-c1c503866097.PNG)
![unluck7](https://user-images.githubusercontent.com/30483063/29351041-b4171aa6-8280-11e7-88ce-6fbe049daada.PNG)
![try7](https://user-images.githubusercontent.com/30483063/29351032-af6c63b2-8280-11e7-8fbe-61ed8fc740be.PNG)
![lucky](https://user-images.githubusercontent.com/30483063/29351054-c33e71d2-8280-11e7-9bea-2c093f715366.PNG)

**Comment by RakenShahi** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lucky.pkg7;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Lucky7 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        int x, c = 0;
        String check = "y";
        Random r = new Random();

        JOptionPane.showMessageDialog(null, "   *******LUCKY 7*******\n Welcome To The Game");
        JOptionPane.showMessageDialog(null, "Its Time to get to know your luck, Click on Ok to continue");
        while (check.equalsIgnoreCase("y")) {
            x = r.nextInt(10);
            JOptionPane.showMessageDialog(null, "You got number : " + x);
            if (x == 7) {
                c++;
                if (c >=2) {
                    check = JOptionPane.showInputDialog("You are very lucky today\nWanna try again once more?\nYes : y\nNo : n");

                }
                check = JOptionPane.showInputDialog("Congratulation, you've got lucky number 7!\nYou have won the game\nAgain do you wish to try your luck?\nYes : y\nNo : n");

            } else {
                check = JOptionPane.showInputDialog("Sorry Bad luck!!!.\n Would you like to try again?(y/n)");
            }
        }

    }
  
}

}

**OUTPUT**
![welcome](https://user-images.githubusercontent.com/30067218/29358917-82835d3a-829c-11e7-93f0-ebfb141b5ec1.PNG)
![its](https://user-images.githubusercontent.com/30067218/29358919-867bd552-829c-11e7-9bb1-f896fe3d84a5.PNG)
![num 2](https://user-images.githubusercontent.com/30067218/29358933-969bf836-829c-11e7-947e-4dda357ae2e8.PNG)
![sory](https://user-images.githubusercontent.com/30067218/29358943-9cc6b732-829c-11e7-9286-3f8a3f1d2e35.PNG)
![luck7](https://user-images.githubusercontent.com/30067218/29358951-a3ad676c-829c-11e7-8733-63296de1c5de.PNG)
![againwish](https://user-images.githubusercontent.com/30067218/29358996-d6fda352-829c-11e7-8839-0ae91b55042c.PNG)
![luck7](https://user-images.githubusercontent.com/30067218/29359034-fe339f94-829c-11e7-92ee-0005442d5f5d.PNG)

![vl](https://user-images.githubusercontent.com/30067218/29358999-dc53e262-829c-11e7-87e7-5a02135ec865.PNG)

**Comment by duwalshraddha** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package luckyseven;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class LuckySeven {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String s = JOptionPane.showInputDialog("Do you wanna know if you are lucky? Enter y or n"), ch = "y";
        while (ch.equalsIgnoreCase("y")) {
            Random r = new Random();
            int x;
            x = r.nextInt(10);
            if (x == 7) {
                System.out.println("Wow!! you are lucky...you got 7");
            } else {
                System.out.println("Sorry the number generated is " + x);
            }
            ch = JOptionPane.showInputDialog("Do you wanna try again?\t\t (y/n)");
        }

    }

}
![1](https://user-images.githubusercontent.com/28709572/29359956-6f631408-82a0-11e7-9bb7-16b801602c20.png)
![2](https://user-images.githubusercontent.com/28709572/29359958-75108c96-82a0-11e7-97c7-7961577e839a.png)
![3](https://user-images.githubusercontent.com/28709572/29359961-78d2851e-82a0-11e7-8508-19ded6ba260a.png)
![4](https://user-images.githubusercontent.com/28709572/29359968-7c5ca688-82a0-11e7-9e2f-49e2461a4574.png)

**Comment by SusanCB** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day13.pkg3;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author nissus
 */
public class Day133 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Random r=new Random();
        JOptionPane.showMessageDialog(null, "  Welcome To Lucky7");
        JOptionPane.showMessageDialog(null, " Lets try your luck");
        JOptionPane.showMessageDialog(null, " Click OK to Generate the number");
        String ch="y";
        while (ch.equalsIgnoreCase("y")){
        int c=r.nextInt(10);
        if (c==7){
            JOptionPane.showMessageDialog(null, "7UP, you are lucky today");
        }
      else
        {JOptionPane.showMessageDialog(null, "Sorry, its"+c+" for you today");
        }
       ch= JOptionPane.showInputDialog(null, " Do you want to try again [Y/N]");
        }
        // TODO code application logic here
    }
    
}
![13 1](https://user-images.githubusercontent.com/30483070/29361506-a060f58c-82a7-11e7-8b7f-c30b7ad5c257.PNG)
![13 2](https://user-images.githubusercontent.com/30483070/29361504-a05f3738-82a7-11e7-8e20-080061986cbd.PNG)
![13 3](https://user-images.githubusercontent.com/30483070/29361502-a05e9e68-82a7-11e7-8919-2ae7a2ab09de.PNG)
![13 4](https://user-images.githubusercontent.com/30483070/29361503-a05eb560-82a7-11e7-9976-400749896293.PNG)
![13 5](https://user-images.githubusercontent.com/30483070/29361507-a060e7b8-82a7-11e7-8186-4c23512e7efc.PNG)
![13 6](https://user-images.githubusercontent.com/30483070/29361505-a0601dce-82a7-11e7-937c-09bd95cf9069.PNG)
![13 7](https://user-images.githubusercontent.com/30483070/29361508-a091bfc8-82a7-11e7-829b-b0eb6cd30741.PNG)

**Comment by raBbn** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lucky7;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author raBbn
 */
public class Lucky7 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        int x, y, z, count = 0;
        String key;
        String ch="y";
        while (ch.equalsIgnoreCase("y")){
        JOptionPane.showMessageDialog(null,"play the game");
        Random r = new Random();
        x = r.nextInt(10);
        y = r.nextInt(10);
        z = r.nextInt(10);
        JOptionPane.showMessageDialog(null, x);
        JOptionPane.showMessageDialog(null, y);
        JOptionPane.showMessageDialog(null, z);
        if (x == 7 || y == 7 || z == 7) {
            JOptionPane.showMessageDialog(null,"you are lucky");
            }
        
        else if (x == 7 && y == 7 && z == 7) {
            JOptionPane.showMessageDialog(null,"you are very lucky");
            }
        
        else{
           JOptionPane.showMessageDialog(null,"you are out of luck ..SORRY");
        }
        
        ch=JOptionPane.showInputDialog("do you want to play again(y/n)??");
        }
    }
}
![capture](https://user-images.githubusercontent.com/30038764/29361705-83e904ca-82a8-11e7-9b11-fd5223cbb031.PNG)
![capture1](https://user-images.githubusercontent.com/30038764/29361706-83f43fde-82a8-11e7-9a1e-1843c3bdf5ff.PNG)
![capture2](https://user-images.githubusercontent.com/30038764/29361707-83f94f4c-82a8-11e7-80e6-5f03a5278f51.PNG)
![capture3](https://user-images.githubusercontent.com/30038764/29361708-83fdefd4-82a8-11e7-9b9e-6344d68ae312.PNG)
![capture4](https://user-images.githubusercontent.com/30038764/29361709-8407542a-82a8-11e7-9b64-87ea454767a6.PNG)
![capture5](https://user-images.githubusercontent.com/30038764/29361710-840e2ffc-82a8-11e7-8891-ade01bfd264f.PNG)

**Comment by AmritDuwal** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bunkerarray;

import java.util.Random;

/**
 *
 * @author Amrit Duwal
 */
public class Randomnumberni {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Random r = new Random();
        int x;
        System.out.println("Enter f6 to start the game");
        x = r.nextInt(10);
        System.out.print(x);
        if (x == 7) {

            System.out.println("\nyou won");
        } else {
            System.out.println("\ntry again enter(f6)");
        }

    }

}
![random](https://user-images.githubusercontent.com/30483092/29363594-63fdd55c-82b0-11e7-94f7-7561974b45bd.JPG)

**Comment by jagdish4249** [comment]
package pkg40lucky7;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author jagdish
 */
public class Main {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        //String luckyNo = JOptionPane.showInputDialog("Press enter to check your luck");
        int Check;
        do{
        Random r = new Random();
        int x;
        x = r.nextInt(9); //nextInt(6)
        if(x==7) 
            JOptionPane.showMessageDialog(null,"You are Mr. Lucky 7 Broda.");
        else
            JOptionPane.showMessageDialog(null,"Sorry. Luck is not with you this time.");
            
         Check = JOptionPane.showConfirmDialog(null,"Lets Check your Luck");
        }while(Check == 0);
        
    }
    
}

![image](https://user-images.githubusercontent.com/11315092/29365546-22ba939e-82b7-11e7-863c-5dc06bac6bd7.png)

![image](https://user-images.githubusercontent.com/11315092/29365569-355273f0-82b7-11e7-9b39-c7bfb1671a04.png)

![image](https://user-images.githubusercontent.com/11315092/29365604-52b78520-82b7-11e7-95e9-4f14e621d77a.png)

**Comment by rabina12** [comment]
public class RandomNumber {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Random r = new Random();
        String ch = "y";
        JOptionPane.showMessageDialog(null, "Welcome");
        while (ch.equalsIgnoreCase("y")) {

            int x = r.nextInt(10);
            if (x != 7) {
                JOptionPane.showMessageDialog(null, "sorry!" + x + "\nbest of luck nexttime");
            } else {
                JOptionPane.showMessageDialog(null, "Congratulation");
            }
            ch = JOptionPane.showInputDialog("Do you want to try your luck again??(y/n)");

        }
    }
}
![c1](https://user-images.githubusercontent.com/30483091/29365677-8fd7355e-82b7-11e7-986b-3bff85c28544.PNG)
![c2](https://user-images.githubusercontent.com/30483091/29365678-8fe905c2-82b7-11e7-8c69-a82a2859ac8e.PNG)
![c3](https://user-images.githubusercontent.com/30483091/29365679-8ff38362-82b7-11e7-8f44-a1a1424bc788.PNG)
![c4](https://user-images.githubusercontent.com/30483091/29365680-8ff6d9cc-82b7-11e7-9935-954ffaf13107.PNG)

**Comment by sarumdr** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lucky7;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author sarumdr
 */
public class Lucky7 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String s = "y";
        while (s.equalsIgnoreCase("y")
          {
            JOptionPane.showMessageDialog(null, "Welcome to Lucky 7 Game");
            JOptionPane.showMessageDialog(null, "lets check your luck");
            Random r = new Random()
            );
        int x = r.nextInt(100);
            if (x == 7) {
                JOptionPane.showMessageDialog(null, "Wow you got 7.\n Your luck is with you");
            } else if (x == 77) {
                JOptionPane.showMessageDialog(null, "superb you got" + x + ".\n super lucky");
            } else if (x == 777) {
                JOptionPane.showMessageDialog(null, "babaal you got" + x + ".\n you will have a great day today");
            } else {
                JOptionPane.showMessageDialog(null, "Oops you got" + x + ".\n May be luck is not with u today.");
                s = JOptionPane.showInputDialog("try again????");

            }
        }
    }
}

}

OUTPUT
![image](https://user-images.githubusercontent.com/29326121/29371180-59f5a1a4-82c7-11e7-9b35-30e1e7ad7c58.png)



![image](https://user-images.githubusercontent.com/29326121/29371321-cd532018-82c7-11e7-9a65-5d2ebbf7368d.png)


![image](https://user-images.githubusercontent.com/29326121/29371872-4ce87d9a-82c9-11e7-88c3-77563edbfee3.png)

**Comment by ajay987** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lucky7;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Lucky7 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Random r = new Random();
        int a = 7;
        String check = "y";
        while (check.equalsIgnoreCase("y")) {
            if (a == r.nextInt(10)) {

                JOptionPane.showMessageDialog(null, "lucky");
            } else {
                JOptionPane.showMessageDialog(null, "notlucky");
            }
            String check1 = JOptionPane.showInputDialog("want to continue?y/n");
            check = check1;
        }
    }

}
![lu1](https://user-images.githubusercontent.com/26328626/29521457-5f19ce26-86a5-11e7-8948-77235421b0a1.PNG)
![lu2](https://user-images.githubusercontent.com/26328626/29521458-5f8fb8c0-86a5-11e7-8f49-6a2043fedeca.PNG)
![lu3](https://user-images.githubusercontent.com/26328626/29521460-5fe8253c-86a5-11e7-9b4a-d3b5cfff81b5.PNG)

**Comment by ghost** [comment]
package randomnumbergeneration;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author User
 */
public class RandomNumberGeneration {

    private static int r1;

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Scanner in = new Scanner(System.in);
        String check = "y";
        while (check.equalsIgnoreCase("y")) {
            System.out.println("Generating random number from 1 to 9...");
            randomm();
            if (r1 == 7) {
                System.out.println("Congratulations!!! You Win");
            } else {
                System.out.println("Sorry! You Lose!!!");
            }
            System.out.println("Would you like to try again? Y/N");
            check = in.next();
        }
    }

    public static void randomm() {
        Random r = new Random();
        r1 = r.nextInt(10);
        System.out.println("The number you got is:" + r1);
        if (r1 == 0) {
            randomm();
        }
    }
}
OUTPUT:
![luckylucky7](https://user-images.githubusercontent.com/30017933/29529620-1fd76cee-86c0-11e7-9dff-467c5b13a5b3.PNG)

**Comment by rituratnam** [comment]
CODE:
package lucky7diag;

import static java.lang.Integer.parseInt;
import static java.time.Clock.system;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Lucky7Diag {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        
        int name;
        String check = "y";
        Random r = new Random();
        int rnd = r.nextInt(7);
        while (check.equalsIgnoreCase("y")){
        name = parseInt(JOptionPane.showInputDialog("Enter a number between 1 and 7 "));
        JOptionPane.showMessageDialog(null, "The number you entered is " + name + "\nThe number generated by computer is " + rnd);
         if( name == rnd ){
        
            JOptionPane.showMessageDialog(null, "Congratulations !!" + "\nYou are so lucky");
        }
        
    else
        {
            JOptionPane.showMessageDialog(null, "Oops !!" + "\nBetter luck next time");
            check = JOptionPane.showInputDialog("Do you want to continue? \nYes : y\nNo : n");
             } 
        }
        
    }
    }
Output:
![p](https://user-images.githubusercontent.com/30037739/29530197-5891d950-86c2-11e7-94da-bb60342dc547.PNG)
![q](https://user-images.githubusercontent.com/30037739/29530219-6a20e21a-86c2-11e7-9ae5-78d4dcdd4b3b.PNG)
![r](https://user-images.githubusercontent.com/30037739/29530228-700bfa5c-86c2-11e7-924a-4061cee47d82.PNG)
![s](https://user-images.githubusercontent.com/30037739/29530233-74ee4a98-86c2-11e7-859a-8e293a564287.PNG)
![t](https://user-images.githubusercontent.com/30037739/29530252-846baef2-86c2-11e7-956a-4b9b7191e4c6.PNG)
![u](https://user-images.githubusercontent.com/30037739/29530259-8cde53f0-86c2-11e7-94f0-650a476328c5.PNG)
![v](https://user-images.githubusercontent.com/30037739/29530261-92c86f3a-86c2-11e7-85fe-176a2462f774.PNG)

**Comment by Sudan15423** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magic7;

import static java.lang.Integer.parseInt;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Dragon15423
 */
public class Magic7 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String ch = (JOptionPane.showInputDialog("Welcome !\nWant to test your luck?(yes/no)")), res = "";

        int[] result = {};
        result = new int[3];
        boolean test = true;
        if (ch.equalsIgnoreCase("yes")) {

            while (test == true) {

                Random r = new Random();
                for (int i = 0; i < result.length; i++) {

                    result[i] = r.nextInt(10);
                    res += result[i] + "";
                    if (result[i] == 7) {
                        System.out.println("You sure are lucky (>.<)");
                    } else {
                        switch (parseInt(res)) {
                            case 77:
                                System.out.println("You are super  lucky (>.<)");
                                break;
                            case 777:
                                System.out.println("Overkill (>.<)");
                                break;
                        }

                    }

                }
                System.out.println("Your number=" + res);

                String ch1 = (JOptionPane.showInputDialog("Want to test your luck again?(yes/no)"));
                test = ch1.equalsIgnoreCase("yes");
                res = "";
            }

        }

    }

}
![magic7](https://user-images.githubusercontent.com/24761050/29574334-f7814456-8780-11e7-98db-40c481eeeaf2.PNG)
![1](https://user-images.githubusercontent.com/24761050/29574384-1cbf8e9e-8781-11e7-9602-41f427448316.PNG)
![2](https://user-images.githubusercontent.com/24761050/29574404-2ca3471a-8781-11e7-9c6f-be305adaf7ec.PNG)
