### ISSUE TITLE
Submit - Own Method Overloading Example

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#41]
Submit - Own Method Overloading Example representing simple but specific problem solving.

**Comment by milan604** [comment]
package exampleoverload;

import static java.lang.Double.parseDouble;
import static java.lang.Float.parseFloat;
import static java.lang.Long.parseLong;
import javax.swing.JOptionPane;

/**
 *
 * @author m-lan
 */
public class ExampleOverload {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        MethodOverload mlan = new MethodOverload();
        System.out.println("Fahrenheit to Degree Centigrade");
        float Fahrenheit;
        double Degree;
        long Kelvin;
        Fahrenheit = parseFloat(JOptionPane.showInputDialog("Enter Fahrenheit "));
        mlan.temperatureConvert(Fahrenheit);
        Degree = parseDouble(JOptionPane.showInputDialog("Enter Degree Centigrade "));
        mlan.temperatureConvert(Degree);
        Kelvin = parseLong(JOptionPane.showInputDialog("Enter Kelvin "));
        mlan.temperatureConvert(Kelvin);
    }

}

**Class MethodOverload**
package exampleoverload;

import javax.swing.JOptionPane;

/**
 *
 * @author m-lan
 */
public class MethodOverload {

    float convert1, convert2;

    void temperatureConvert(float f) {
        convert1 = (5 / 9.0f) * (f - 32);
        convert2 = (5 / 9.0f) * (f - 32) + 273;
        JOptionPane.showMessageDialog(null, "Degree Centigrade of " + f + " Fahrenheit is " + convert1 + "\nKelvin of " + f + " Fahrenheit is " + convert2);
    }

    void temperatureConvert(double d) {
        double convert = ((9 / 5.0 * d) + 32);
        double convert3 = d + 273;
        JOptionPane.showMessageDialog(null, "Fahrenheit of " + d + " Celsius is " + convert + "\nKelvin of " + d + " celsius is " + convert3);

    }

    void temperatureConvert(long k) {
        long con1 = k - 273;
        long con2 = (9 / 5 * (k - 273) + 32);
        JOptionPane.showMessageDialog(null, "Degree Centigrade of " + k + " Kelvin is " + con1 + "\nFahrenheit of" + k + " Kelvin is " + con2);
    }
}

**Output**
![screenshot from 2017-08-18 09-13-49](https://user-images.githubusercontent.com/30483005/29443155-eb5816c0-83f5-11e7-89c8-e8578546d22f.png)
![screenshot from 2017-08-18 09-14-06](https://user-images.githubusercontent.com/30483005/29443158-f15db08e-83f5-11e7-8dc6-529e7766861f.png)
![screenshot from 2017-08-18 09-14-58](https://user-images.githubusercontent.com/30483005/29443174-04dd94b2-83f6-11e7-8c2f-a945b0a435bc.png)
![screenshot from 2017-08-18 09-14-24](https://user-images.githubusercontent.com/30483005/29443181-0c92cde4-83f6-11e7-82bd-94f294a14ca9.png)

**Comment by jagdish4249** [comment]
package methodoverloading17august1;

/**
 *
 * @author Jagdish Duwal
 */

class Add{
    int sum(int a, int b){
        return a+b;
    }

    int sum(int a, int b,int c) {
        return a+b+c;
    }

    int sum(int a, int b,int... c) {

        int s=0;
        for (int x:c) {
            s+=x;
        }
        return a+b+s;
    }
}
public class MethodOverLoading17August1 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {


        //Method Overloading
        System.out.println("Method Overloading");

        Add a = new Add();

        System.out.println(a.sum(1,2));;
        System.out.println(a.sum(1,2,3));
        System.out.println(a.sum(1,2,3,4));


    }

}

![image](https://user-images.githubusercontent.com/11315092/29454510-3464fc7a-842d-11e7-8b95-cb2c3ee2901f.png)

**Comment by AmritDuwal** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package functionoverriding;

/**
 *
 * @author Amrit Duwal
 */
public class Functionoverriding {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Nepalidate obj = new Nepalidate();
        int bdate[] = {2052, 9, 12};
        obj.date(bdate);
    }

}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package functionoverriding;

/**
 *
 * @author Amrit Duwal
 */
public class EnglishDate {

    int year, month, day;

    void date(int x[]) {
        year = x[0] - 57;
        month = x[1] + 3;

        day = x[2] - 13;
        if (day < 0) {
            month++;
            day = day + 30;
        }
        if (month > 12) {
            year--;
            month = month - 12;
        }

        System.out.println("English date of birth  " + year + '/' + month + '/' + day);
    }

}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package functionoverriding;

/**
 *
 * @author Amrit Duwal
 */
public class Nepalidate extends EnglishDate {

    int a;

    void date(int x[]) {
        super.date(x);

        a = 2074 - x[0];
        System.out.println("Nepali date of birth " + x[0] + '/' + x[1] + '/' + x[2]);
    }

}
![dateofbirht](https://user-images.githubusercontent.com/30483092/29486633-8dfa5dba-850a-11e7-85c5-5ba4997a2f08.JPG)

**Comment by ajay987** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package methodovermul;

/**
 *
 * @author Dell
 */
public class Mul {

    public int calmul(int m) {
        int n = 0;
        for (int i = 1; i <= 10; i++) {
            int x = m * i;
            n = n + x;
        }

        return n;
    }

    public int calmul(int m, int n, int p) {
        int count = 0;
        for (int i = 1; i <= 10; i++) {
            int x = m * i;
            int y = n * i;
            int z = p * i;
            count = count + x + y + z;
        }
        return count;

    }
}


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package methodovermul;

/**
 *
 * @author Dell
 */
public class MethodOverMul {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Mul m = new Mul();
        System.out.println("sumOfMul2:" + m.calmul(2));
        System.out.println("sumOfMul2,3,4:" + m.calmul(2, 3, 4));
    }

}
![mol](https://user-images.githubusercontent.com/26328626/29525548-caae87e6-86b2-11e7-81ac-bd14a6d3bd34.PNG)

**Comment by RakenShahi** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overloadingtask;

/**
 *
 * @author DELL
 */
public class OverloadingTask {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Overloaded N = new Overloaded();
        N.show('z');
        N.show('x', (byte) 10);
    }

}


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overloadingtask;

/**
 *
 * @author DELL
 */
public class Overloaded {

    public void show(char c) {
        System.out.println(c);

    }

    public void show(char c, byte a) {
        System.out.println(c + "=" + a);
    }

}


**OUTPUT**
![overloading](https://user-images.githubusercontent.com/30067218/29670978-0a0e8f06-8908-11e7-8683-e73c206af8b3.PNG)
