### ISSUE TITLE
Submit - Own Method Overriding Example

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#42]
Submit - Own Method Overriding Example representing simple but specific problem solving.

**Comment by milan604** [comment]
package overridesampleexample;

/**
 *
 * @author m-lan
 */
public class OverrideSampleExample {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Kelvin temp = new Kelvin();
        System.out.println("Temperature Conversion");
        temp.convert(32);
    }

}

class Degree {

    void convert(float DegreeC) {

        System.out.println("The Degree Centigrade is " + DegreeC);
    }

}

class Fahrenheit extends Degree {

    @Override
    void convert(float DegreeC) {
        super.convert(DegreeC);
        float fah = (9 / 5.0f * DegreeC + 32);
        System.out.println("The Fahrenheit of" + DegreeC + " Centigrade is " + fah);
    }
}

class Kelvin extends Fahrenheit {

    @Override
    void convert(float DegreeC) {
        super.convert(DegreeC);
        float Kelvin = DegreeC + 273;
        System.out.println("The Kelvin of" + DegreeC + " Centigrade is " + Kelvin);
    }
}

![screenshot from 2017-08-18 09-44-33](https://user-images.githubusercontent.com/30483005/29443743-e3451718-83f9-11e7-8c66-eb9f6333e47e.png)

**Comment by jagdish4249** [comment]
package methodoverriding17august2;

/**
 *
 * @author Jagdish Duwal
 */

class Auto{
    
    void start(){

        System.out.println("Starting...");
    }
    
}

class Truck extends Auto{
    @Override
    void start(){
        super.start();
        System.out.println("Truck ignition...");
    }
}



public class MethodOverriding17August2 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
       Truck t = new Truck();
        t.start();
    }
    
}

![image](https://user-images.githubusercontent.com/11315092/29454583-6c9feffa-842d-11e7-96aa-8a67d4b4dc62.png)

**Comment by RakenShahi** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapro;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
class Java {

    void test() {
       
        JOptionPane.showMessageDialog(null, "******Input Your number******");
    }

}

class Pro extends Java {

    @Override
    void test() {
        super.test();
        int a;

        a = Integer.parseInt(JOptionPane.showInputDialog(null, "Input your number"));
        JOptionPane.showMessageDialog(null, "Your entered number = " + a);
        //System.out.println("You entered number = " + a);
    }
}

public class JavaPro {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        Pro p = new Pro();
        p.test();
    }

}

**OUTPUT**
![over1](https://user-images.githubusercontent.com/30067218/29496002-7accb906-85e9-11e7-985c-07649ef0056e.PNG)
![over2](https://user-images.githubusercontent.com/30067218/29496005-80ad61ea-85e9-11e7-9e6e-6d935612807b.PNG)
![over3](https://user-images.githubusercontent.com/30067218/29496007-86e33d0a-85e9-11e7-9540-b5079db1ddd2.PNG)

**Comment by ajay987** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
public class ManyClass {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        NEC n = new NEC();
        System.out.println("@@@@@@@@@@@@@ admitstudent@@@@@@@@@@@@@@");
        n.admitStudent();
        System.out.println("@@@@@@@@@@@@@@publishResult@@@@@@@@@@@@@@");
        n.publishresult();
    }

}




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
abstract class College {

    public abstract void admitStudent();

    public abstract void publishresult();
}

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
public class WRC1 extends College {

    public void admitStudent() {
        System.out.println("Admit Student by WRC1");
    }

    public void publishresult() {
        System.out.println("Publish Result WRC1");
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
public class KhEC extends WRC1 {

    public void admitStudent() {
        super.admitStudent();
        System.out.println("Admit Student by KhEC");
    }

    public void publishresult() {
        super.publishresult();
        System.out.println("Publish Result KhEC");
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
public class KhCE extends KhEC {

    public void admitStudent() {
        super.admitStudent();
        System.out.println("Admit Student by KhCE");
    }

    public void publishresult() {
        super.publishresult();
        System.out.println("Publish Result KhCE");
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
public class KhSS extends KhCE {

    public void admitStudent() {
        super.admitStudent();
        System.out.println("Admit Student by KhSS");
    }

    public void publishresult() {
        super.publishresult();
        System.out.println("Publish Result KhSS");
    }
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manyclass;

/**
 *
 * @author Dell
 */
public class NEC extends KhSS {

    public void admitStudent() {
        super.admitStudent();
        System.out.println("Admit Student by NEC");
    }

    public void publishresult() {
        super.publishresult();
        System.out.println("Publish Result NEC");
    }
}
![rid](https://user-images.githubusercontent.com/26328626/29570858-6364050a-8777-11e7-9b50-1701d6078b44.PNG)
