### ISSUE TITLE
Submit - Initial Screenshots, Source Code & Database

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#64]
- Initial Screenshots of SMS
- Source Code
- Database

**Comment by ErSKS** [comment]
![01](https://user-images.githubusercontent.com/5508421/29799975-28590d6a-8c87-11e7-9008-3c084b16fd55.png)

![02](https://user-images.githubusercontent.com/5508421/29799967-228e0188-8c87-11e7-9e27-edabda3aeebc.png)

![02_02](https://user-images.githubusercontent.com/5508421/29799970-236302f2-8c87-11e7-8022-d2384cece38a.png)

![03](https://user-images.githubusercontent.com/5508421/29799969-2349443e-8c87-11e7-9ed8-f7af5b23a055.png)

![04](https://user-images.githubusercontent.com/5508421/29799972-238b0ee6-8c87-11e7-83bd-b70a30090c97.png)

![05](https://user-images.githubusercontent.com/5508421/29799976-295bd134-8c87-11e7-8228-f0dffeb384dd.png)

![06](https://user-images.githubusercontent.com/5508421/29799971-236f043a-8c87-11e7-89d2-541b6fa3604f.png)

[SMS.zip](https://github.com/ErSKS/Java/files/1258815/SMS.zip)

[java_db.txt](https://github.com/ErSKS/Java/files/1258819/java_db.txt)

**Comment by AmritDuwal** [comment]
![Uploading Screen Shot 2017-08-29 at 7.22.28 PM.png…]()
![screen shot 2017-08-29 at 7 23 07 pm](https://user-images.githubusercontent.com/30483092/29824101-478da45c-8cf0-11e7-87df-b9c2b6b1f87f.png)

![screen shot 2017-08-29 at 7 26 28 pm](https://user-images.githubusercontent.com/30483092/29824102-478e4902-8cf0-11e7-83d9-7ac43f77326b.png)

![screen shot 2017-08-29 at 7 26 36 pm](https://user-images.githubusercontent.com/30483092/29824103-4791a354-8cf0-11e7-8d80-4728fcff9633.png)

![screen shot 2017-08-29 at 7 26 43 pm](https://user-images.githubusercontent.com/30483092/29824104-4794ef32-8cf0-11e7-8d78-82e2a50ad0b1.png)



[JavaApplication99.zip](https://github.com/ErSKS/Java/files/1260498/JavaApplication99.zip)

[java_dbb.txt](https://github.com/ErSKS/Java/files/1260501/java_dbb.txt)

**Comment by milan604** [comment]
![1](https://user-images.githubusercontent.com/30483005/29832061-b43d5eba-8d06-11e7-8240-0843bfd91268.png)


![2](https://user-images.githubusercontent.com/30483005/29832062-b65a90a0-8d06-11e7-8d8a-51432946ba57.png)


![3](https://user-images.githubusercontent.com/30483005/29832067-b8132a38-8d06-11e7-8bb2-320c3338ed4c.png)


![4](https://user-images.githubusercontent.com/30483005/29832072-ba973b82-8d06-11e7-8dac-99320ec404fe.png)


![5](https://user-images.githubusercontent.com/30483005/29832075-bc0029ca-8d06-11e7-9a86-2cfd7f3c0c30.png)


![6](https://user-images.githubusercontent.com/30483005/29832078-bd9e969a-8d06-11e7-8a6e-4746e6c7f0f2.png)

![7](https://user-images.githubusercontent.com/30483005/29832083-c1299ad0-8d06-11e7-93d5-1569572efb3d.png)


[School.zip](https://github.com/ErSKS/Java/files/1260970/School.zip)
[School.txt](https://github.com/ErSKS/Java/files/1260978/School.txt)

**Comment by RakenShahi** [comment]
![login](https://user-images.githubusercontent.com/30067218/29878428-390acc3e-8dc2-11e7-90b4-33b3e61410fd.PNG)
![studentmgmt](https://user-images.githubusercontent.com/30067218/29878427-390a9066-8dc2-11e7-8053-98d24427d7fd.PNG)
![add](https://user-images.githubusercontent.com/30067218/29878429-39136470-8dc2-11e7-8c14-380e26e8d19e.PNG)

[DbLogin.zip](https://github.com/ErSKS/Java/files/1264013/DbLogin.zip)
[java_db (1).txt](https://github.com/ErSKS/Java/files/1264014/java_db.1.txt)
