### ISSUE TITLE
Design & Develop a Simple Calculator

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#66]
![calculator](https://user-images.githubusercontent.com/5508421/29913274-6950636c-8e54-11e7-85e2-d5267c440093.png)

**Comment by milan604** [comment]
![screenshot from 2017-08-31 18-52-28](https://user-images.githubusercontent.com/30483005/29924788-dd5d922e-8e7d-11e7-85f0-4d823e430a4c.png)

[Calculator.zip](https://github.com/ErSKS/Java/files/1267129/Calculator.zip)

**Comment by Sudan15423** [comment]
![calc](https://user-images.githubusercontent.com/24761050/29926434-31b32d3e-8e83-11e7-801c-ac158ce8e781.PNG)
![calc2](https://user-images.githubusercontent.com/24761050/29926443-36b1f1d0-8e83-11e7-93d0-2cbd95d949b9.PNG)
[Calc.zip](https://github.com/ErSKS/Java/files/1267290/Calc.zip)

**Comment by karmi214** [comment]
[Calculator.zip](https://github.com/ErSKS/Java/files/1267359/Calculator.zip)
![capture](https://user-images.githubusercontent.com/24736628/29927968-823d7580-8e87-11e7-83e6-4067cf512799.PNG)

**Comment by sajanbasnet75** [comment]
![callc](https://user-images.githubusercontent.com/22407698/29934059-82245d2c-8e99-11e7-8266-8c3580ed9223.PNG)


[Calculatorr.zip](https://github.com/ErSKS/Java/files/1267804/Calculatorr.zip)

**Comment by ajay987** [comment]
[Calculator.zip](https://github.com/ErSKS/Java/files/1268079/Calculator.zip)
![c1](https://user-images.githubusercontent.com/26328626/29938322-1d2d6062-8ea8-11e7-8731-b63680133b9c.PNG)
![c2](https://user-images.githubusercontent.com/26328626/29938321-1d2bf33a-8ea8-11e7-8720-4507f49d3f09.PNG)

**Comment by rituratnam** [comment]
[Calculator.zip](https://github.com/ErSKS/Java/files/1268915/Calculator.zip)
![calcul](https://user-images.githubusercontent.com/30037739/29952020-53849b9c-8ee6-11e7-8db3-3c65c6f7c8d3.PNG)
![process](https://user-images.githubusercontent.com/30037739/29952021-586e9a36-8ee6-11e7-9686-8e72a70cbba0.PNG)
![output](https://user-images.githubusercontent.com/30037739/29952022-5bda64e8-8ee6-11e7-9edc-1f916ef33ee9.PNG)
![pi](https://user-images.githubusercontent.com/30037739/29952026-5e8bb8fe-8ee6-11e7-9af6-76cabcc2556d.PNG)

**Comment by RakenShahi** [comment]
[Calculator.zip](https://github.com/ErSKS/Java/files/1270202/Calculator.zip)
![calculator](https://user-images.githubusercontent.com/30067218/29970060-d6f20fd0-8f42-11e7-8aca-3246106cae92.PNG)

**Comment by rabina12** [comment]
![c1](https://user-images.githubusercontent.com/30483091/29971457-044e11ae-8f48-11e7-9fe3-3a894ccae1c4.PNG)
![c2](https://user-images.githubusercontent.com/30483091/29971459-045845c0-8f48-11e7-9086-a9b00e56b81d.PNG)
![c3](https://user-images.githubusercontent.com/30483091/29971458-0456bec6-8f48-11e7-9274-2ceb744212fb.PNG)
![c4](https://user-images.githubusercontent.com/30483091/29971460-045f5a22-8f48-11e7-99ac-149d222b3cdb.PNG)
[Calculator.zip](https://github.com/ErSKS/Java/files/1270317/Calculator.zip)

**Comment by ragenmah** [comment]
[Calculator.zip](https://github.com/ErSKS/Java/files/1271840/Calculator.zip)
![fullscreen capture 922017 75946 am](https://user-images.githubusercontent.com/30024247/29992192-78b3df34-8fb5-11e7-8715-cd4286d6fcaf.jpg)
