### ISSUE TITLE
Develop - PIN Breaker

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#67]
Develop a Java program to break/crack/detect entered pin. And how much cycle will it take to break for the PIN **8848**?

**Comment by Sudan15423** [comment]
![bruteinput](https://user-images.githubusercontent.com/24761050/29974831-ef803700-8f53-11e7-853f-fabcfa20d0c8.PNG)
![brute](https://user-images.githubusercontent.com/24761050/29974838-f406b876-8f53-11e7-88f6-0fbd788566cd.PNG)
[Brute.zip](https://github.com/ErSKS/Java/files/1270582/Brute.zip)

**Comment by milan604** [comment]
![screenshot from 2017-09-01 07-02-10](https://user-images.githubusercontent.com/30483005/29951647-b9c7bfcc-8ee3-11e7-84f2-d3ba67748a8a.png)

![screenshot from 2017-09-01 07-02-27](https://user-images.githubusercontent.com/30483005/29951663-c5cc17c8-8ee3-11e7-9d47-87019b9fdf30.png)

[PinCracker.zip](https://github.com/ErSKS/Java/files/1268893/PinCracker.zip)

**Comment by ErSKS** [comment]
@Sudan15423 It may take **3645 trails** to break PIN **8848**. Enhance your code by using reference of @milan604

**Comment by Rocken1** [comment]
![crack1](https://user-images.githubusercontent.com/30067218/29972818-2b456adc-8f4d-11e7-8bb1-9016d6d1d1cf.PNG)
![crack2](https://user-images.githubusercontent.com/30067218/29972821-2ed8e912-8f4d-11e7-9f6f-8972fc565eec.PNG)
[PinCrack.zip](https://github.com/ErSKS/Java/files/1270430/PinCrack.zip)
