### ISSUE TITLE
Refresh JTable

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#68]
Code to refresh JTable:
DefaultTableModel v = (DefaultTableModel) tblStd.getModel();
v.setRowCount(0);

//Load Data - You have that code on windowFormOpened()

**Comment by milan604** [comment]
DefaultTableModel t = (DefaultTableModel) table_student.getModel();
        int rowCount = t.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            t.removeRow(i);
        }

**Comment by jagdish4249** [comment]
![01](https://user-images.githubusercontent.com/11315092/29951125-3efe18fc-8ee0-11e7-97ad-478e0d6b447e.JPG)

![02](https://user-images.githubusercontent.com/11315092/29951124-3efc7c54-8ee0-11e7-9222-dd20fc6c5211.JPG)

![03](https://user-images.githubusercontent.com/11315092/29951127-3f11f9ee-8ee0-11e7-97a9-b5ed8f094e73.JPG)

![04](https://user-images.githubusercontent.com/11315092/29951126-3f10f04e-8ee0-11e7-9563-cb17e7030f24.JPG)

![05](https://user-images.githubusercontent.com/11315092/29951128-3f143330-8ee0-11e7-923a-39cacd96a810.JPG)

**Comment by jagdish4249** [comment]
Update_table() function ko sql ma SELECT * FROM `student` ko satta chaine colum matra nikaleni huncha

download rs2xml.jar from http://www.4shared.one/file/kfogUJTTba/rs2xml.html
