### ISSUE TITLE
Submit your Project Title

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/Java#70]
Submit your project title here ...

**Comment by milan604** [comment]
E-Voting System for Nepal

**Comment by raBbn** [comment]
Phone Book

**Comment by jagdish4249** [comment]
Minimart Billing

**Comment by ghost** [comment]
Patient's Information System

**Comment by sajanbasnet75** [comment]
Human Resource (Employee) Management System

**Comment by rabina12** [comment]
Library Management System

**Comment by maheshyakami** [comment]
Art Gallery

**Comment by nabinbikramsah** [comment]
electricity billing system

**Comment by leoprabin** [comment]
Blood Bank repository

**Comment by duwalshraddha** [comment]
FIR Management System

**Comment by sarumdr** [comment]
Gym management system

**Comment by Roshanshrestha7** [comment]
Auto Show

**Comment by PujanChangubhari** [comment]
Result Management System

**Comment by RakenShahi** [comment]
Shop management

**Comment by rituratnam** [comment]
Pharmacy Management System

**Comment by Sudan15423** [comment]
**Human anatomy application**

**Comment by ragenmah** [comment]
Fruit And Vegetable Management System

**Comment by Schandboy** [comment]
Attendance System

**Comment by kiir33** [comment]
MCQ Tester

**Comment by sushant2222** [comment]
pharmacy billing system

**Comment by ghost** [comment]
Fashion Model Management System

**Comment by kajalmaharjan** [comment]
Tours and Travels Management System

**Comment by sanzeevtamang** [comment]
Finance management System

**Comment by luckydivya** [comment]
clothing management system

**Comment by karmi214** [comment]
Event Management System

**Comment by syslin** [comment]
Blood Bank Management System

**Comment by rituratnam** [comment]
Apartment Management System
